#!/bin/bash

adb devices > status.config

status=$(sed -i '1d' status.config && awk '{print $2}' status.config)

while [[ $status != "device" ]]; do

echo "Click ok on your Android device to authorize access via adb"
adb devices > status.config
done

while [[ $status = "device" ]]; do

while read -rp "Do you wanna uninstall Mi Video? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Mi Video..."
        adb shell pm uninstall -k --user 0 com.miui.videoplayer
        break
        ;;
    "y") echo "Uninstalling Mi Video..."
        adb shell pm uninstall -k --user 0 com.miui.videoplayer        
        break       
        ;;

    "Y") echo "Uninstalling Mi Video..."
        adb shell pm uninstall -k --user 0 com.miui.videoplayer   
        break       
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Mi Music? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Mi Music..."
        adb shell pm uninstall -k --user 0 com.miui.player
        break
        ;;
    "y") echo "Uninstalling Mi Music..."
        adb shell pm uninstall -k --user 0 com.miui.player       
        break       
        ;;

    "Y") echo "Uninstalling Mi Music..."
        adb shell pm uninstall -k --user 0 com.miui.player 
        break       
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Mi File Manager? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Mi File Manager..."
        adb shell pm uninstall -k --user 0 com.mi.android.globalFileexplorer
        break
        ;;
    "y") echo "Uninstalling Mi File Manager..."
        adb shell pm uninstall -k --user 0 com.mi.android.globalFileexplorer      
        break       
        ;;

    "Y") echo "Uninstalling Mi File Manager..."
        adb shell pm uninstall -k --user 0 com.mi.android.globalFileexplorer 
        break       
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Mi Calculator? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Mi Calculator..."
        adb shell pm uninstall -k --user 0 com.miui.calculator
        break
        ;;
    "y") echo "Uninstalling Mi Calculator..."
        adb shell pm uninstall -k --user 0 com.miui.calculator
        break
        ;;

    "Y") echo "Uninstalling Mi Calculator..."
        adb shell pm uninstall -k --user 0 com.miui.calculator
        break
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Mi Compass? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Mi Compass..."
        adb shell pm uninstall -k --user 0 com.miui.compass
        break
        ;;
    "y") echo "Uninstalling Mi Compass..."
        adb shell pm uninstall -k --user 0 com.miui.compass
        break
        ;;

    "Y") echo "Uninstalling Mi Compass..."
        adb shell pm uninstall -k --user 0 com.miui.compass
        break
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Mi Notes? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Mi Notes..."
        adb shell pm uninstall -k --user 0 com.miui.notes
        break
        ;;
    "y") echo "Uninstalling Mi Notes..."
        adb shell pm uninstall -k --user 0 com.miui.notes
        break
        ;;

    "Y") echo "Uninstalling Mi Notes..."
        adb shell pm uninstall -k --user 0 com.miui.notes
        break
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Mi Screen recorder? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Mi Screen recorder..."
        adb shell pm uninstall -k --user 0 com.miui.screenrecorder
        break
        ;;
    "y") echo "Uninstalling Mi Screen recorder..."
        adb shell pm uninstall -k --user 0 com.miui.screenrecorder       
        break       
        ;;

    "Y") echo "Uninstalling Mi Screen recorder..."
        adb shell pm uninstall -k --user 0 com.miui.screenrecorder  
        break       
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Xiaomi Game Center? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Xiaomi Game Center..."
        adb shell pm uninstall -k --user 0 com.xiaomi.glgm
        break
        ;;
    "y") echo "Uninstalling Xiaomi Game Center..."
        adb shell pm uninstall -k --user 0 com.xiaomi.glgm
        break
        ;;

    "Y") echo "Uninstalling Xiaomi Game Center..."
        adb shell pm uninstall -k --user 0 com.xiaomi.glgm
        break
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Xiaomi ShareMe? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Xiaomi ShareMe..."
        adb shell pm uninstall -k --user 0 com.xiaomi.midrop
        break
        ;;
    "y") echo "Uninstalling Xiaomi ShareMe..."
        adb shell pm uninstall -k --user 0 com.xiaomi.midrop        
        break       
        ;;

    "Y") echo "Uninstalling Xiaomi ShareMe..."
        adb shell pm uninstall -k --user 0 com.xiaomi.midrop        
        break       
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done

while read -rp "Do you wanna uninstall Xiaomi Scanner? [Y/n] " && [[ $REPLY != "q" ]]; do
case $REPLY in
    "") echo "Uninstalling Xiaomi Scanner..."
        adb shell pm uninstall -k --user 0 com.xiaomi.scanner
        break
        ;;
    "y") echo "Uninstalling Xiaomi Scanner..."
        adb shell pm uninstall -k --user 0 com.xiaomi.scanner       
        break       
        ;;

    "Y") echo "Uninstalling Xiaomi Scanner..."
        adb shell pm uninstall -k --user 0 com.xiaomi.scanner        
        break       
        ;;

    "n") echo "Skipping..."
        break
        ;;

    "N") echo "Skipping..."
        break
        ;;

    *) echo "Invalid input";;
esac
done
done
